services:
  backend:
    build: ./backend
    image: eduub_backend:latest
    container_name: eduub-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - CHROMA_URL=http://eduub-chromadb:8000
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
      - CORS_ORIGINS=http://64.227.152.247:5173,http://localhost:5173,https://eduub.mano.systems,https://eduubserver.mano.systems
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./backend/temp:/app/controllers/temp
    depends_on:
      - chromadb
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    image: eduub_frontend:latest
    container_name: eduub-frontend
    ports:
      - "5173:80"
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - CORS_ORIGINS=http://64.227.152.247:5173,http://localhost:5173,https://eduub.mano.systems,https://eduubserver.mano.systems
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: eduub-chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma-data:/chroma/chroma
    environment:
      - PERSIST_DIRECTORY=/chroma/chroma
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge